<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Pookie.Audio.Tests" />
    <PackageReference Include="SoundFlow" Version="1.4.1" GeneratePathProperty="true" />
    <PackageReference Include="SoundFlow.Codecs.FFMpeg" Version="1.4.0" GeneratePathProperty="true" />
  </ItemGroup>
</Project>
