<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="..\Pookie.Media\Pookie.Media.csproj" />
  </ItemGroup>
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Pookie</AssemblyName>
  </PropertyGroup>
  <Import Project="Pookie.App.Shared.props" />
</Project>
