<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <AssemblyName>Pookie</AssemblyName>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' and $(RuntimeIdentifier.StartsWith('linux-'))">
    <DefineConstants>$(DefineConstants);POOKIE_LINUX</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' and $(RuntimeIdentifier.StartsWith('win-'))">
    <DefineConstants>$(DefineConstants);POOKIE_WINDOWS</DefineConstants>
  </PropertyGroup>
  <PropertyGroup Condition="'$(RuntimeIdentifier)' != '' and $(RuntimeIdentifier.StartsWith('osx-'))">
    <DefineConstants>$(DefineConstants);POOKIE_MACOS</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <EmbeddedResource Include="Auth/login-capture.js" />
    <EmbeddedResource Include="Auth/browser-requests.js" />
    <EmbeddedResource Include="Assets/Icons/*.svg" />
    <EmbeddedResource Include="Assets/logo.svg" />
    <EmbeddedResource Include="Assets/Branding/*" />
    <EmbeddedResource Include="Assets/Fonts/GoogleSans.ttf" />
    <EmbeddedResource Include="Assets/Fonts/Bungee-Regular.ttf" />
    <PackageReference Include="Aprillz.MewUI" Version="0.22.1" />
    <PackageReference Include="InfiniLore.InfiniFrame" Version="0.62.1" />
    <ProjectReference Include="../Pookie.SoundCloud/Pookie.SoundCloud.csproj" />
    <ProjectReference Include="../Pookie.Audio/Pookie.Audio.csproj" />
    <ProjectReference Include="../Pookie.Discord/Pookie.Discord.csproj" />
  </ItemGroup>
</Project>
